import Head from "next/head";
import Container from "react-bootstrap/Container";
import Image from "next/image";
import { Inter } from "next/font/google";
import Slider from "./../components/Slider";
import SliderCayegory from "@/components/SliderCayegory";
import ProductSection from "@/components/product/ProductSection";






const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>acos store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="homePage" id="homePage">
        <Container>
          <Slider />
          <SliderCayegory />
          <ProductSection />
        </Container>
      </section>
    </>
  );
}
